services:
  app:
    build: .
    ports:
      - "8500:8500"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
      - GCP_PROJECT_ID=kp-seo-blog-automator
      - GCP_LOCATION=us-central1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/kp-seo-agent-key.json
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    volumes:
      - ./app:/app/app
      - ./frontend:/app/frontend
      - ./credentials:/app/credentials
    depends_on:
      db:
          condition: service_healthy
      rabbitmq:
          condition: service_healthy
      chromadb:
          condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8500 --reload

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 5s
      timeout: 3s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
  chromadb:
    image: chromadb/chroma:0.4.24 # Pinning to a stable version
    ports:
      - "8001:8000" # Exposing Chroma on host port 8001 to avoid conflict with FastAPI
    volumes:
      - chroma_data:/chroma/.chroma/index
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/heartbeat')\""]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
  chroma_data:
