services:
  - type: web
    name: kp-seo-auto-commenter
    runtime: docker
    region: singapore
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: POSTGRES_SERVER
        fromDatabase:
          name: kp-seo-db
          property: host
      - key: POSTGRES_USER
        fromDatabase:
          name: kp-seo-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: kp-seo-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: kp-seo-db
          property: database
      - key: GCP_PROJECT_ID
        value: kp-seo-blog-automator
      - key: GCP_LOCATION
        value: us-central1
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /app/credentials/kp-seo-agent-key.json
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

databases:
  - name: kp-seo-db
    plan: free
    region: singapore