services:
  - type: web
    name: kp-seo-blog-automator
    env: docker
    plan: free
    healthCheckPath: / # Render uses this to check if your app is running
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kpseodb # Your correct DB name
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false # This marks it as a secret to be set only in the dashboard

databases:
  - name: kpseodb
    plan: free